// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type LifeCycleState string

const (
	LifeCycleState_CREATING  LifeCycleState = "CREATING"
	LifeCycleState_AVAILABLE LifeCycleState = "AVAILABLE"
	LifeCycleState_UPDATING  LifeCycleState = "UPDATING"
	LifeCycleState_DELETING  LifeCycleState = "DELETING"
	LifeCycleState_DELETED   LifeCycleState = "DELETED"
	LifeCycleState_ERROR     LifeCycleState = "ERROR"
)

type PerformanceMode string

const (
	PerformanceMode_GENERAL_PURPOSE PerformanceMode = "GENERAL_PURPOSE"
	PerformanceMode_MAX_IO          PerformanceMode = "MAX_IO"
)

type ReplicationOverwriteProtection string

const (
	ReplicationOverwriteProtection_ENABLED     ReplicationOverwriteProtection = "ENABLED"
	ReplicationOverwriteProtection_DISABLED    ReplicationOverwriteProtection = "DISABLED"
	ReplicationOverwriteProtection_REPLICATING ReplicationOverwriteProtection = "REPLICATING"
)

type ReplicationStatus string

const (
	ReplicationStatus_ENABLED  ReplicationStatus = "ENABLED"
	ReplicationStatus_ENABLING ReplicationStatus = "ENABLING"
	ReplicationStatus_DELETING ReplicationStatus = "DELETING"
	ReplicationStatus_ERROR    ReplicationStatus = "ERROR"
	ReplicationStatus_PAUSED   ReplicationStatus = "PAUSED"
	ReplicationStatus_PAUSING  ReplicationStatus = "PAUSING"
)

type Resource string

const (
	Resource_FileSystem  Resource = "FileSystem"
	Resource_MountTarget Resource = "MountTarget"
)

type ResourceIDType string

const (
	ResourceIDType_LongId  ResourceIDType = "LongId"
	ResourceIDType_ShortId ResourceIDType = "ShortId"
)

type Status string

const (
	Status_ENABLED   Status = "ENABLED"
	Status_ENABLING  Status = "ENABLING"
	Status_DISABLED  Status = "DISABLED"
	Status_DISABLING Status = "DISABLING"
)

type ThroughputMode string

const (
	ThroughputMode_BURSTING    ThroughputMode = "BURSTING"
	ThroughputMode_PROVISIONED ThroughputMode = "PROVISIONED"
	ThroughputMode_ELASTIC     ThroughputMode = "ELASTIC"
)

type TransitionToArchiveRules string

const (
	TransitionToArchiveRules_AFTER_7_DAYS   TransitionToArchiveRules = "AFTER_7_DAYS"
	TransitionToArchiveRules_AFTER_30_DAYS  TransitionToArchiveRules = "AFTER_30_DAYS"
	TransitionToArchiveRules_AFTER_90_DAYS  TransitionToArchiveRules = "AFTER_90_DAYS"
	TransitionToArchiveRules_AFTER_180_DAYS TransitionToArchiveRules = "AFTER_180_DAYS"
	TransitionToArchiveRules_AFTER_365_DAYS TransitionToArchiveRules = "AFTER_365_DAYS"
	TransitionToArchiveRules_AFTER_1_DAY    TransitionToArchiveRules = "AFTER_1_DAY"
	TransitionToArchiveRules_AFTER_60_DAYS  TransitionToArchiveRules = "AFTER_60_DAYS"
	TransitionToArchiveRules_AFTER_270_DAYS TransitionToArchiveRules = "AFTER_270_DAYS"
	TransitionToArchiveRules_AFTER_14_DAYS  TransitionToArchiveRules = "AFTER_14_DAYS"
)

type TransitionToIARules string

const (
	TransitionToIARules_AFTER_30_DAYS  TransitionToIARules = "AFTER_30_DAYS"
	TransitionToIARules_AFTER_90_DAYS  TransitionToIARules = "AFTER_90_DAYS"
	TransitionToIARules_AFTER_180_DAYS TransitionToIARules = "AFTER_180_DAYS"
	TransitionToIARules_AFTER_1_DAY    TransitionToIARules = "AFTER_1_DAY"
	TransitionToIARules_AFTER_270_DAYS TransitionToIARules = "AFTER_270_DAYS"
	TransitionToIARules_AFTER_365_DAYS TransitionToIARules = "AFTER_365_DAYS"
	TransitionToIARules_AFTER_7_DAYS   TransitionToIARules = "AFTER_7_DAYS"
	TransitionToIARules_AFTER_14_DAYS  TransitionToIARules = "AFTER_14_DAYS"
	TransitionToIARules_AFTER_60_DAYS  TransitionToIARules = "AFTER_60_DAYS"
)

type TransitionToPrimaryStorageClassRules string

const (
	TransitionToPrimaryStorageClassRules_AFTER_1_ACCESS TransitionToPrimaryStorageClassRules = "AFTER_1_ACCESS"
)
