//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoint) DeepCopyInto(out *AccessPoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoint.
func (in *AccessPoint) DeepCopy() *AccessPoint {
	if in == nil {
		return nil
	}
	out := new(AccessPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessPoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointAlreadyExists) DeepCopyInto(out *AccessPointAlreadyExists) {
	*out = *in
	if in.AccessPointID != nil {
		in, out := &in.AccessPointID, &out.AccessPointID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointAlreadyExists.
func (in *AccessPointAlreadyExists) DeepCopy() *AccessPointAlreadyExists {
	if in == nil {
		return nil
	}
	out := new(AccessPointAlreadyExists)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointDescription) DeepCopyInto(out *AccessPointDescription) {
	*out = *in
	if in.AccessPointARN != nil {
		in, out := &in.AccessPointARN, &out.AccessPointARN
		*out = new(string)
		**out = **in
	}
	if in.AccessPointID != nil {
		in, out := &in.AccessPointID, &out.AccessPointID
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.PosixUser != nil {
		in, out := &in.PosixUser, &out.PosixUser
		*out = new(PosixUser)
		(*in).DeepCopyInto(*out)
	}
	if in.RootDirectory != nil {
		in, out := &in.RootDirectory, &out.RootDirectory
		*out = new(RootDirectory)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointDescription.
func (in *AccessPointDescription) DeepCopy() *AccessPointDescription {
	if in == nil {
		return nil
	}
	out := new(AccessPointDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointList) DeepCopyInto(out *AccessPointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointList.
func (in *AccessPointList) DeepCopy() *AccessPointList {
	if in == nil {
		return nil
	}
	out := new(AccessPointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessPointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointSpec) DeepCopyInto(out *AccessPointSpec) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.FileSystemRef != nil {
		in, out := &in.FileSystemRef, &out.FileSystemRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.PosixUser != nil {
		in, out := &in.PosixUser, &out.PosixUser
		*out = new(PosixUser)
		(*in).DeepCopyInto(*out)
	}
	if in.RootDirectory != nil {
		in, out := &in.RootDirectory, &out.RootDirectory
		*out = new(RootDirectory)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointSpec.
func (in *AccessPointSpec) DeepCopy() *AccessPointSpec {
	if in == nil {
		return nil
	}
	out := new(AccessPointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointStatus) DeepCopyInto(out *AccessPointStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AccessPointID != nil {
		in, out := &in.AccessPointID, &out.AccessPointID
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointStatus.
func (in *AccessPointStatus) DeepCopy() *AccessPointStatus {
	if in == nil {
		return nil
	}
	out := new(AccessPointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicy) DeepCopyInto(out *BackupPolicy) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicy.
func (in *BackupPolicy) DeepCopy() *BackupPolicy {
	if in == nil {
		return nil
	}
	out := new(BackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateAccessPointOutput) DeepCopyInto(out *CreateAccessPointOutput) {
	*out = *in
	if in.AccessPointARN != nil {
		in, out := &in.AccessPointARN, &out.AccessPointARN
		*out = new(string)
		**out = **in
	}
	if in.AccessPointID != nil {
		in, out := &in.AccessPointID, &out.AccessPointID
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.PosixUser != nil {
		in, out := &in.PosixUser, &out.PosixUser
		*out = new(PosixUser)
		(*in).DeepCopyInto(*out)
	}
	if in.RootDirectory != nil {
		in, out := &in.RootDirectory, &out.RootDirectory
		*out = new(RootDirectory)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateAccessPointOutput.
func (in *CreateAccessPointOutput) DeepCopy() *CreateAccessPointOutput {
	if in == nil {
		return nil
	}
	out := new(CreateAccessPointOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateAccessPointRequest) DeepCopyInto(out *CreateAccessPointRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.PosixUser != nil {
		in, out := &in.PosixUser, &out.PosixUser
		*out = new(PosixUser)
		(*in).DeepCopyInto(*out)
	}
	if in.RootDirectory != nil {
		in, out := &in.RootDirectory, &out.RootDirectory
		*out = new(RootDirectory)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateAccessPointRequest.
func (in *CreateAccessPointRequest) DeepCopy() *CreateAccessPointRequest {
	if in == nil {
		return nil
	}
	out := new(CreateAccessPointRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateFileSystemRequest) DeepCopyInto(out *CreateFileSystemRequest) {
	*out = *in
	if in.AvailabilityZoneName != nil {
		in, out := &in.AvailabilityZoneName, &out.AvailabilityZoneName
		*out = new(string)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(bool)
		**out = **in
	}
	if in.Encrypted != nil {
		in, out := &in.Encrypted, &out.Encrypted
		*out = new(bool)
		**out = **in
	}
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.PerformanceMode != nil {
		in, out := &in.PerformanceMode, &out.PerformanceMode
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ThroughputMode != nil {
		in, out := &in.ThroughputMode, &out.ThroughputMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateFileSystemRequest.
func (in *CreateFileSystemRequest) DeepCopy() *CreateFileSystemRequest {
	if in == nil {
		return nil
	}
	out := new(CreateFileSystemRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateMountTargetOutput) DeepCopyInto(out *CreateMountTargetOutput) {
	*out = *in
	if in.AvailabilityZoneID != nil {
		in, out := &in.AvailabilityZoneID, &out.AvailabilityZoneID
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZoneName != nil {
		in, out := &in.AvailabilityZoneName, &out.AvailabilityZoneName
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.MountTargetID != nil {
		in, out := &in.MountTargetID, &out.MountTargetID
		*out = new(string)
		**out = **in
	}
	if in.NetworkInterfaceID != nil {
		in, out := &in.NetworkInterfaceID, &out.NetworkInterfaceID
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateMountTargetOutput.
func (in *CreateMountTargetOutput) DeepCopy() *CreateMountTargetOutput {
	if in == nil {
		return nil
	}
	out := new(CreateMountTargetOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateMountTargetRequest) DeepCopyInto(out *CreateMountTargetRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateMountTargetRequest.
func (in *CreateMountTargetRequest) DeepCopy() *CreateMountTargetRequest {
	if in == nil {
		return nil
	}
	out := new(CreateMountTargetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateReplicationConfigurationRequest) DeepCopyInto(out *CreateReplicationConfigurationRequest) {
	*out = *in
	if in.SourceFileSystemID != nil {
		in, out := &in.SourceFileSystemID, &out.SourceFileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateReplicationConfigurationRequest.
func (in *CreateReplicationConfigurationRequest) DeepCopy() *CreateReplicationConfigurationRequest {
	if in == nil {
		return nil
	}
	out := new(CreateReplicationConfigurationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateTagsRequest) DeepCopyInto(out *CreateTagsRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateTagsRequest.
func (in *CreateTagsRequest) DeepCopy() *CreateTagsRequest {
	if in == nil {
		return nil
	}
	out := new(CreateTagsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreationInfo) DeepCopyInto(out *CreationInfo) {
	*out = *in
	if in.OwnerGID != nil {
		in, out := &in.OwnerGID, &out.OwnerGID
		*out = new(int64)
		**out = **in
	}
	if in.OwnerUID != nil {
		in, out := &in.OwnerUID, &out.OwnerUID
		*out = new(int64)
		**out = **in
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreationInfo.
func (in *CreationInfo) DeepCopy() *CreationInfo {
	if in == nil {
		return nil
	}
	out := new(CreationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAccessPointRequest) DeepCopyInto(out *DeleteAccessPointRequest) {
	*out = *in
	if in.AccessPointID != nil {
		in, out := &in.AccessPointID, &out.AccessPointID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAccessPointRequest.
func (in *DeleteAccessPointRequest) DeepCopy() *DeleteAccessPointRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteAccessPointRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteFileSystemPolicyRequest) DeepCopyInto(out *DeleteFileSystemPolicyRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteFileSystemPolicyRequest.
func (in *DeleteFileSystemPolicyRequest) DeepCopy() *DeleteFileSystemPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteFileSystemPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteFileSystemRequest) DeepCopyInto(out *DeleteFileSystemRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteFileSystemRequest.
func (in *DeleteFileSystemRequest) DeepCopy() *DeleteFileSystemRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteFileSystemRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteMountTargetRequest) DeepCopyInto(out *DeleteMountTargetRequest) {
	*out = *in
	if in.MountTargetID != nil {
		in, out := &in.MountTargetID, &out.MountTargetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteMountTargetRequest.
func (in *DeleteMountTargetRequest) DeepCopy() *DeleteMountTargetRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteMountTargetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteReplicationConfigurationRequest) DeepCopyInto(out *DeleteReplicationConfigurationRequest) {
	*out = *in
	if in.SourceFileSystemID != nil {
		in, out := &in.SourceFileSystemID, &out.SourceFileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteReplicationConfigurationRequest.
func (in *DeleteReplicationConfigurationRequest) DeepCopy() *DeleteReplicationConfigurationRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteReplicationConfigurationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteTagsRequest) DeepCopyInto(out *DeleteTagsRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteTagsRequest.
func (in *DeleteTagsRequest) DeepCopy() *DeleteTagsRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteTagsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeAccessPointsRequest) DeepCopyInto(out *DescribeAccessPointsRequest) {
	*out = *in
	if in.AccessPointID != nil {
		in, out := &in.AccessPointID, &out.AccessPointID
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeAccessPointsRequest.
func (in *DescribeAccessPointsRequest) DeepCopy() *DescribeAccessPointsRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeAccessPointsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeAccessPointsResponse) DeepCopyInto(out *DescribeAccessPointsResponse) {
	*out = *in
	if in.AccessPoints != nil {
		in, out := &in.AccessPoints, &out.AccessPoints
		*out = make([]*CreateAccessPointOutput, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CreateAccessPointOutput)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeAccessPointsResponse.
func (in *DescribeAccessPointsResponse) DeepCopy() *DescribeAccessPointsResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeAccessPointsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeAccountPreferencesRequest) DeepCopyInto(out *DescribeAccountPreferencesRequest) {
	*out = *in
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeAccountPreferencesRequest.
func (in *DescribeAccountPreferencesRequest) DeepCopy() *DescribeAccountPreferencesRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeAccountPreferencesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeAccountPreferencesResponse) DeepCopyInto(out *DescribeAccountPreferencesResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeAccountPreferencesResponse.
func (in *DescribeAccountPreferencesResponse) DeepCopy() *DescribeAccountPreferencesResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeAccountPreferencesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeBackupPolicyRequest) DeepCopyInto(out *DescribeBackupPolicyRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeBackupPolicyRequest.
func (in *DescribeBackupPolicyRequest) DeepCopy() *DescribeBackupPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeBackupPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeFileSystemPolicyRequest) DeepCopyInto(out *DescribeFileSystemPolicyRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeFileSystemPolicyRequest.
func (in *DescribeFileSystemPolicyRequest) DeepCopy() *DescribeFileSystemPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeFileSystemPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeFileSystemsRequest) DeepCopyInto(out *DescribeFileSystemsRequest) {
	*out = *in
	if in.CreationToken != nil {
		in, out := &in.CreationToken, &out.CreationToken
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.Marker != nil {
		in, out := &in.Marker, &out.Marker
		*out = new(string)
		**out = **in
	}
	if in.MaxItems != nil {
		in, out := &in.MaxItems, &out.MaxItems
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeFileSystemsRequest.
func (in *DescribeFileSystemsRequest) DeepCopy() *DescribeFileSystemsRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeFileSystemsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeFileSystemsResponse) DeepCopyInto(out *DescribeFileSystemsResponse) {
	*out = *in
	if in.FileSystems != nil {
		in, out := &in.FileSystems, &out.FileSystems
		*out = make([]*FileSystemDescription, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(FileSystemDescription)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Marker != nil {
		in, out := &in.Marker, &out.Marker
		*out = new(string)
		**out = **in
	}
	if in.NextMarker != nil {
		in, out := &in.NextMarker, &out.NextMarker
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeFileSystemsResponse.
func (in *DescribeFileSystemsResponse) DeepCopy() *DescribeFileSystemsResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeFileSystemsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeLifecycleConfigurationRequest) DeepCopyInto(out *DescribeLifecycleConfigurationRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeLifecycleConfigurationRequest.
func (in *DescribeLifecycleConfigurationRequest) DeepCopy() *DescribeLifecycleConfigurationRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeLifecycleConfigurationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeMountTargetSecurityGroupsRequest) DeepCopyInto(out *DescribeMountTargetSecurityGroupsRequest) {
	*out = *in
	if in.MountTargetID != nil {
		in, out := &in.MountTargetID, &out.MountTargetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeMountTargetSecurityGroupsRequest.
func (in *DescribeMountTargetSecurityGroupsRequest) DeepCopy() *DescribeMountTargetSecurityGroupsRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeMountTargetSecurityGroupsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeMountTargetSecurityGroupsResponse) DeepCopyInto(out *DescribeMountTargetSecurityGroupsResponse) {
	*out = *in
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeMountTargetSecurityGroupsResponse.
func (in *DescribeMountTargetSecurityGroupsResponse) DeepCopy() *DescribeMountTargetSecurityGroupsResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeMountTargetSecurityGroupsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeMountTargetsRequest) DeepCopyInto(out *DescribeMountTargetsRequest) {
	*out = *in
	if in.AccessPointID != nil {
		in, out := &in.AccessPointID, &out.AccessPointID
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.Marker != nil {
		in, out := &in.Marker, &out.Marker
		*out = new(string)
		**out = **in
	}
	if in.MaxItems != nil {
		in, out := &in.MaxItems, &out.MaxItems
		*out = new(int64)
		**out = **in
	}
	if in.MountTargetID != nil {
		in, out := &in.MountTargetID, &out.MountTargetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeMountTargetsRequest.
func (in *DescribeMountTargetsRequest) DeepCopy() *DescribeMountTargetsRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeMountTargetsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeMountTargetsResponse) DeepCopyInto(out *DescribeMountTargetsResponse) {
	*out = *in
	if in.Marker != nil {
		in, out := &in.Marker, &out.Marker
		*out = new(string)
		**out = **in
	}
	if in.MountTargets != nil {
		in, out := &in.MountTargets, &out.MountTargets
		*out = make([]*CreateMountTargetOutput, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CreateMountTargetOutput)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NextMarker != nil {
		in, out := &in.NextMarker, &out.NextMarker
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeMountTargetsResponse.
func (in *DescribeMountTargetsResponse) DeepCopy() *DescribeMountTargetsResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeMountTargetsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeReplicationConfigurationsRequest) DeepCopyInto(out *DescribeReplicationConfigurationsRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeReplicationConfigurationsRequest.
func (in *DescribeReplicationConfigurationsRequest) DeepCopy() *DescribeReplicationConfigurationsRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeReplicationConfigurationsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeReplicationConfigurationsResponse) DeepCopyInto(out *DescribeReplicationConfigurationsResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeReplicationConfigurationsResponse.
func (in *DescribeReplicationConfigurationsResponse) DeepCopy() *DescribeReplicationConfigurationsResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeReplicationConfigurationsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeTagsRequest) DeepCopyInto(out *DescribeTagsRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.Marker != nil {
		in, out := &in.Marker, &out.Marker
		*out = new(string)
		**out = **in
	}
	if in.MaxItems != nil {
		in, out := &in.MaxItems, &out.MaxItems
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeTagsRequest.
func (in *DescribeTagsRequest) DeepCopy() *DescribeTagsRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeTagsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeTagsResponse) DeepCopyInto(out *DescribeTagsResponse) {
	*out = *in
	if in.Marker != nil {
		in, out := &in.Marker, &out.Marker
		*out = new(string)
		**out = **in
	}
	if in.NextMarker != nil {
		in, out := &in.NextMarker, &out.NextMarker
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeTagsResponse.
func (in *DescribeTagsResponse) DeepCopy() *DescribeTagsResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeTagsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Destination) DeepCopyInto(out *Destination) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.LastReplicatedTimestamp != nil {
		in, out := &in.LastReplicatedTimestamp, &out.LastReplicatedTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Destination.
func (in *Destination) DeepCopy() *Destination {
	if in == nil {
		return nil
	}
	out := new(Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationToCreate) DeepCopyInto(out *DestinationToCreate) {
	*out = *in
	if in.AvailabilityZoneName != nil {
		in, out := &in.AvailabilityZoneName, &out.AvailabilityZoneName
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationToCreate.
func (in *DestinationToCreate) DeepCopy() *DestinationToCreate {
	if in == nil {
		return nil
	}
	out := new(DestinationToCreate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystem) DeepCopyInto(out *FileSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystem.
func (in *FileSystem) DeepCopy() *FileSystem {
	if in == nil {
		return nil
	}
	out := new(FileSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FileSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemAlreadyExists) DeepCopyInto(out *FileSystemAlreadyExists) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemAlreadyExists.
func (in *FileSystemAlreadyExists) DeepCopy() *FileSystemAlreadyExists {
	if in == nil {
		return nil
	}
	out := new(FileSystemAlreadyExists)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemDescription) DeepCopyInto(out *FileSystemDescription) {
	*out = *in
	if in.AvailabilityZoneID != nil {
		in, out := &in.AvailabilityZoneID, &out.AvailabilityZoneID
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZoneName != nil {
		in, out := &in.AvailabilityZoneName, &out.AvailabilityZoneName
		*out = new(string)
		**out = **in
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.Encrypted != nil {
		in, out := &in.Encrypted, &out.Encrypted
		*out = new(bool)
		**out = **in
	}
	if in.FileSystemARN != nil {
		in, out := &in.FileSystemARN, &out.FileSystemARN
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.FileSystemProtection != nil {
		in, out := &in.FileSystemProtection, &out.FileSystemProtection
		*out = new(UpdateFileSystemProtectionOutput)
		(*in).DeepCopyInto(*out)
	}
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NumberOfMountTargets != nil {
		in, out := &in.NumberOfMountTargets, &out.NumberOfMountTargets
		*out = new(int64)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.PerformanceMode != nil {
		in, out := &in.PerformanceMode, &out.PerformanceMode
		*out = new(string)
		**out = **in
	}
	if in.SizeInBytes != nil {
		in, out := &in.SizeInBytes, &out.SizeInBytes
		*out = new(FileSystemSize)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ThroughputMode != nil {
		in, out := &in.ThroughputMode, &out.ThroughputMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemDescription.
func (in *FileSystemDescription) DeepCopy() *FileSystemDescription {
	if in == nil {
		return nil
	}
	out := new(FileSystemDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemList) DeepCopyInto(out *FileSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FileSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemList.
func (in *FileSystemList) DeepCopy() *FileSystemList {
	if in == nil {
		return nil
	}
	out := new(FileSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FileSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemProtectionDescription) DeepCopyInto(out *FileSystemProtectionDescription) {
	*out = *in
	if in.ReplicationOverwriteProtection != nil {
		in, out := &in.ReplicationOverwriteProtection, &out.ReplicationOverwriteProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemProtectionDescription.
func (in *FileSystemProtectionDescription) DeepCopy() *FileSystemProtectionDescription {
	if in == nil {
		return nil
	}
	out := new(FileSystemProtectionDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemSize) DeepCopyInto(out *FileSystemSize) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(int64)
		**out = **in
	}
	if in.ValueInArchive != nil {
		in, out := &in.ValueInArchive, &out.ValueInArchive
		*out = new(int64)
		**out = **in
	}
	if in.ValueInIA != nil {
		in, out := &in.ValueInIA, &out.ValueInIA
		*out = new(int64)
		**out = **in
	}
	if in.ValueInStandard != nil {
		in, out := &in.ValueInStandard, &out.ValueInStandard
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemSize.
func (in *FileSystemSize) DeepCopy() *FileSystemSize {
	if in == nil {
		return nil
	}
	out := new(FileSystemSize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemSpec) DeepCopyInto(out *FileSystemSpec) {
	*out = *in
	if in.AvailabilityZoneName != nil {
		in, out := &in.AvailabilityZoneName, &out.AvailabilityZoneName
		*out = new(string)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(bool)
		**out = **in
	}
	if in.BackupPolicy != nil {
		in, out := &in.BackupPolicy, &out.BackupPolicy
		*out = new(BackupPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Encrypted != nil {
		in, out := &in.Encrypted, &out.Encrypted
		*out = new(bool)
		**out = **in
	}
	if in.FileSystemProtection != nil {
		in, out := &in.FileSystemProtection, &out.FileSystemProtection
		*out = new(UpdateFileSystemProtectionInput)
		(*in).DeepCopyInto(*out)
	}
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyRef != nil {
		in, out := &in.KMSKeyRef, &out.KMSKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.LifecyclePolicies != nil {
		in, out := &in.LifecyclePolicies, &out.LifecyclePolicies
		*out = make([]*LifecyclePolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LifecyclePolicy)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.PerformanceMode != nil {
		in, out := &in.PerformanceMode, &out.PerformanceMode
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ThroughputMode != nil {
		in, out := &in.ThroughputMode, &out.ThroughputMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemSpec.
func (in *FileSystemSpec) DeepCopy() *FileSystemSpec {
	if in == nil {
		return nil
	}
	out := new(FileSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemStatus) DeepCopyInto(out *FileSystemStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AvailabilityZoneID != nil {
		in, out := &in.AvailabilityZoneID, &out.AvailabilityZoneID
		*out = new(string)
		**out = **in
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NumberOfMountTargets != nil {
		in, out := &in.NumberOfMountTargets, &out.NumberOfMountTargets
		*out = new(int64)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.SizeInBytes != nil {
		in, out := &in.SizeInBytes, &out.SizeInBytes
		*out = new(FileSystemSize)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemStatus.
func (in *FileSystemStatus) DeepCopy() *FileSystemStatus {
	if in == nil {
		return nil
	}
	out := new(FileSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecyclePolicy) DeepCopyInto(out *LifecyclePolicy) {
	*out = *in
	if in.TransitionToArchive != nil {
		in, out := &in.TransitionToArchive, &out.TransitionToArchive
		*out = new(string)
		**out = **in
	}
	if in.TransitionToIA != nil {
		in, out := &in.TransitionToIA, &out.TransitionToIA
		*out = new(string)
		**out = **in
	}
	if in.TransitionToPrimaryStorageClass != nil {
		in, out := &in.TransitionToPrimaryStorageClass, &out.TransitionToPrimaryStorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecyclePolicy.
func (in *LifecyclePolicy) DeepCopy() *LifecyclePolicy {
	if in == nil {
		return nil
	}
	out := new(LifecyclePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListTagsForResourceRequest) DeepCopyInto(out *ListTagsForResourceRequest) {
	*out = *in
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListTagsForResourceRequest.
func (in *ListTagsForResourceRequest) DeepCopy() *ListTagsForResourceRequest {
	if in == nil {
		return nil
	}
	out := new(ListTagsForResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListTagsForResourceResponse) DeepCopyInto(out *ListTagsForResourceResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListTagsForResourceResponse.
func (in *ListTagsForResourceResponse) DeepCopy() *ListTagsForResourceResponse {
	if in == nil {
		return nil
	}
	out := new(ListTagsForResourceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyMountTargetSecurityGroupsRequest) DeepCopyInto(out *ModifyMountTargetSecurityGroupsRequest) {
	*out = *in
	if in.MountTargetID != nil {
		in, out := &in.MountTargetID, &out.MountTargetID
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyMountTargetSecurityGroupsRequest.
func (in *ModifyMountTargetSecurityGroupsRequest) DeepCopy() *ModifyMountTargetSecurityGroupsRequest {
	if in == nil {
		return nil
	}
	out := new(ModifyMountTargetSecurityGroupsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountTarget) DeepCopyInto(out *MountTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountTarget.
func (in *MountTarget) DeepCopy() *MountTarget {
	if in == nil {
		return nil
	}
	out := new(MountTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MountTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountTargetDescription) DeepCopyInto(out *MountTargetDescription) {
	*out = *in
	if in.AvailabilityZoneID != nil {
		in, out := &in.AvailabilityZoneID, &out.AvailabilityZoneID
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZoneName != nil {
		in, out := &in.AvailabilityZoneName, &out.AvailabilityZoneName
		*out = new(string)
		**out = **in
	}
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.MountTargetID != nil {
		in, out := &in.MountTargetID, &out.MountTargetID
		*out = new(string)
		**out = **in
	}
	if in.NetworkInterfaceID != nil {
		in, out := &in.NetworkInterfaceID, &out.NetworkInterfaceID
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountTargetDescription.
func (in *MountTargetDescription) DeepCopy() *MountTargetDescription {
	if in == nil {
		return nil
	}
	out := new(MountTargetDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountTargetList) DeepCopyInto(out *MountTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MountTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountTargetList.
func (in *MountTargetList) DeepCopy() *MountTargetList {
	if in == nil {
		return nil
	}
	out := new(MountTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MountTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountTargetSpec) DeepCopyInto(out *MountTargetSpec) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.FileSystemRef != nil {
		in, out := &in.FileSystemRef, &out.FileSystemRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroupRefs != nil {
		in, out := &in.SecurityGroupRefs, &out.SecurityGroupRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.SubnetRef != nil {
		in, out := &in.SubnetRef, &out.SubnetRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountTargetSpec.
func (in *MountTargetSpec) DeepCopy() *MountTargetSpec {
	if in == nil {
		return nil
	}
	out := new(MountTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountTargetStatus) DeepCopyInto(out *MountTargetStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AvailabilityZoneID != nil {
		in, out := &in.AvailabilityZoneID, &out.AvailabilityZoneID
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZoneName != nil {
		in, out := &in.AvailabilityZoneName, &out.AvailabilityZoneName
		*out = new(string)
		**out = **in
	}
	if in.LifeCycleState != nil {
		in, out := &in.LifeCycleState, &out.LifeCycleState
		*out = new(string)
		**out = **in
	}
	if in.MountTargetID != nil {
		in, out := &in.MountTargetID, &out.MountTargetID
		*out = new(string)
		**out = **in
	}
	if in.NetworkInterfaceID != nil {
		in, out := &in.NetworkInterfaceID, &out.NetworkInterfaceID
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountTargetStatus.
func (in *MountTargetStatus) DeepCopy() *MountTargetStatus {
	if in == nil {
		return nil
	}
	out := new(MountTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PosixUser) DeepCopyInto(out *PosixUser) {
	*out = *in
	if in.GID != nil {
		in, out := &in.GID, &out.GID
		*out = new(int64)
		**out = **in
	}
	if in.SecondaryGIDs != nil {
		in, out := &in.SecondaryGIDs, &out.SecondaryGIDs
		*out = make([]*int64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(int64)
				**out = **in
			}
		}
	}
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PosixUser.
func (in *PosixUser) DeepCopy() *PosixUser {
	if in == nil {
		return nil
	}
	out := new(PosixUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutBackupPolicyRequest) DeepCopyInto(out *PutBackupPolicyRequest) {
	*out = *in
	if in.BackupPolicy != nil {
		in, out := &in.BackupPolicy, &out.BackupPolicy
		*out = new(BackupPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutBackupPolicyRequest.
func (in *PutBackupPolicyRequest) DeepCopy() *PutBackupPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(PutBackupPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutFileSystemPolicyRequest) DeepCopyInto(out *PutFileSystemPolicyRequest) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutFileSystemPolicyRequest.
func (in *PutFileSystemPolicyRequest) DeepCopy() *PutFileSystemPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(PutFileSystemPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutLifecycleConfigurationRequest) DeepCopyInto(out *PutLifecycleConfigurationRequest) {
	*out = *in
	if in.LifecyclePolicies != nil {
		in, out := &in.LifecyclePolicies, &out.LifecyclePolicies
		*out = make([]*LifecyclePolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LifecyclePolicy)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutLifecycleConfigurationRequest.
func (in *PutLifecycleConfigurationRequest) DeepCopy() *PutLifecycleConfigurationRequest {
	if in == nil {
		return nil
	}
	out := new(PutLifecycleConfigurationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationConfigurationDescription) DeepCopyInto(out *ReplicationConfigurationDescription) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.OriginalSourceFileSystemARN != nil {
		in, out := &in.OriginalSourceFileSystemARN, &out.OriginalSourceFileSystemARN
		*out = new(string)
		**out = **in
	}
	if in.SourceFileSystemARN != nil {
		in, out := &in.SourceFileSystemARN, &out.SourceFileSystemARN
		*out = new(string)
		**out = **in
	}
	if in.SourceFileSystemID != nil {
		in, out := &in.SourceFileSystemID, &out.SourceFileSystemID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationConfigurationDescription.
func (in *ReplicationConfigurationDescription) DeepCopy() *ReplicationConfigurationDescription {
	if in == nil {
		return nil
	}
	out := new(ReplicationConfigurationDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootDirectory) DeepCopyInto(out *RootDirectory) {
	*out = *in
	if in.CreationInfo != nil {
		in, out := &in.CreationInfo, &out.CreationInfo
		*out = new(CreationInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootDirectory.
func (in *RootDirectory) DeepCopy() *RootDirectory {
	if in == nil {
		return nil
	}
	out := new(RootDirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagResourceRequest) DeepCopyInto(out *TagResourceRequest) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagResourceRequest.
func (in *TagResourceRequest) DeepCopy() *TagResourceRequest {
	if in == nil {
		return nil
	}
	out := new(TagResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateFileSystemProtectionInput) DeepCopyInto(out *UpdateFileSystemProtectionInput) {
	*out = *in
	if in.ReplicationOverwriteProtection != nil {
		in, out := &in.ReplicationOverwriteProtection, &out.ReplicationOverwriteProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateFileSystemProtectionInput.
func (in *UpdateFileSystemProtectionInput) DeepCopy() *UpdateFileSystemProtectionInput {
	if in == nil {
		return nil
	}
	out := new(UpdateFileSystemProtectionInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateFileSystemProtectionOutput) DeepCopyInto(out *UpdateFileSystemProtectionOutput) {
	*out = *in
	if in.ReplicationOverwriteProtection != nil {
		in, out := &in.ReplicationOverwriteProtection, &out.ReplicationOverwriteProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateFileSystemProtectionOutput.
func (in *UpdateFileSystemProtectionOutput) DeepCopy() *UpdateFileSystemProtectionOutput {
	if in == nil {
		return nil
	}
	out := new(UpdateFileSystemProtectionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateFileSystemProtectionRequest) DeepCopyInto(out *UpdateFileSystemProtectionRequest) {
	*out = *in
	if in.ReplicationOverwriteProtection != nil {
		in, out := &in.ReplicationOverwriteProtection, &out.ReplicationOverwriteProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateFileSystemProtectionRequest.
func (in *UpdateFileSystemProtectionRequest) DeepCopy() *UpdateFileSystemProtectionRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateFileSystemProtectionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateFileSystemRequest) DeepCopyInto(out *UpdateFileSystemRequest) {
	*out = *in
	if in.FileSystemID != nil {
		in, out := &in.FileSystemID, &out.FileSystemID
		*out = new(string)
		**out = **in
	}
	if in.ThroughputMode != nil {
		in, out := &in.ThroughputMode, &out.ThroughputMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateFileSystemRequest.
func (in *UpdateFileSystemRequest) DeepCopy() *UpdateFileSystemRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateFileSystemRequest)
	in.DeepCopyInto(out)
	return out
}
